language: android
script:
  - git fetch origin --tags
  - make debug
git:
  submodules: false
jdk:
    - oraclejdk8
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - platform-tools
    - build-tools-25.0.3
    - android-25
